---
- name: Converge
  hosts: all
  become: true
  become_method: sudo

  vars:
    accounts_users:
    - name: test_user
      uid: 4001
      state: present
      groups:
      - sudo
      public_keys:
      - key: ssh-rsa AAA...
        state: present
    accounts_host_users:
    - name: test_user_2
      uid: 4002
      state: present
      groups: []
      public_keys:
      - key: ssh-rsa AAABBB...
        state: present

  tasks:
  - name: "Include andrelohmann.accounts"
    include_role:
      name: "andrelohmann.accounts"
...
